/* Contenido legal de Ciphra (Términos y Privacidad) en es/en/pt.
 * Lo renderizan terminos.html y privacidad.html. El español es la versión autoritativa
 * (Ciphra opera bajo ley argentina); en/pt son traducciones de cortesía.
 * Reemplazá CONTACT_EMAIL / SITE si cambian. */
(function () {
  const CONTACT_EMAIL = "contacto@ciphra.ai";
  const SITE = "ciphra.com";

  const LEGAL = {
    terminos: {
      es: [
        { h: "1. Aceptación de los Términos", p: "<p>Al acceder y utilizar Ciphra (en adelante, \"la Plataforma\"), el usuario acepta en su totalidad los presentes Términos y Condiciones de Uso (en adelante, \"los Términos\"). Si no estás de acuerdo con alguna de estas condiciones, te pedimos que te abstengas de utilizar la Plataforma.</p><p>El uso continuado de Ciphra después de cualquier modificación a estos Términos implica la aceptación de dichas modificaciones.</p>" },
        { h: "2. Descripción del Servicio", p: "<p>Ciphra es una plataforma de estudio potenciada por inteligencia artificial, diseñada para acompañar el aprendizaje de sus usuarios a través de distintos módulos interactivos, entre ellos:</p><ul><li><b>MindShift:</b> sistema de evaluación en múltiples formatos.</li><li><b>Quantum:</b> resolución de problemas con metodología socrática.</li><li><b>Commander:</b> asistente de IA central con diferentes niveles de capacidad (Synapse, Apex y Ethos).</li></ul><p>La Plataforma se encuentra en desarrollo activo. Ciphra se reserva el derecho de incorporar nuevas funciones, modificar las existentes o discontinuar módulos sin previo aviso.</p>" },
        { h: "3. Elegibilidad y Registro", p: "<p>Para utilizar Ciphra, el usuario debe:</p><ul><li>Tener al menos 13 años de edad. Los menores de 18 años deberán contar con el consentimiento de un padre, madre o tutor legal para registrarse y utilizar la Plataforma.</li><li>Proporcionar información veraz, completa y actualizada durante el proceso de registro.</li><li>Mantener la confidencialidad de sus credenciales de acceso. Ciphra no se responsabiliza por el uso no autorizado de una cuenta derivado de la negligencia del usuario en la protección de sus datos de acceso.</li></ul>" },
        { h: "4. Uso Aceptable", p: "<p>El usuario se compromete a utilizar Ciphra exclusivamente con fines educativos y de manera compatible con la legislación argentina vigente y con estos Términos.</p><p>Queda expresamente prohibido:</p><ul><li>Utilizar la Plataforma para generar, distribuir o almacenar contenido ilegal, engañoso, difamatorio, obsceno o que viole derechos de terceros.</li><li>Intentar acceder a áreas restringidas del sistema, vulnerar mecanismos de seguridad o realizar ingeniería inversa sobre la Plataforma.</li><li>Usar herramientas automatizadas (bots, scrapers u otros) para extraer datos de la Plataforma sin autorización expresa.</li><li>Suplantar la identidad de otros usuarios o de integrantes del equipo de Ciphra.</li><li>Compartir, vender o ceder credenciales de acceso a terceros.</li></ul><p>El incumplimiento de estas condiciones podrá derivar en la suspensión o cancelación permanente de la cuenta, sin perjuicio de las acciones legales que pudieran corresponder.</p>" },
        { h: "5. Inteligencia Artificial y Limitaciones", p: "<p>Ciphra integra modelos de inteligencia artificial de terceros para potenciar su funcionalidad. El usuario reconoce y acepta que:</p><ul><li>Las respuestas generadas por los modelos de IA son de carácter orientativo y no reemplazan el criterio de un profesional ni constituyen asesoramiento académico formal.</li><li>La IA puede cometer errores, generar información desactualizada o producir respuestas imprecisas. Ciphra no garantiza la exactitud, completitud ni idoneidad del contenido generado por sus módulos de IA.</li><li>El procesamiento de ciertos datos puede involucrar infraestructura de proveedores externos (como Google LLC u otros), sujeto a sus propias políticas de privacidad y términos de servicio.</li></ul><p>El usuario es el único responsable del uso que haga del contenido generado por la Plataforma.</p>" },
        { h: "6. Propiedad Intelectual", p: "<p>Todo el contenido original de Ciphra —incluyendo, sin limitación, el diseño de la interfaz, el código fuente, los logotipos, los textos institucionales y la arquitectura de los módulos— es propiedad exclusiva de Ciphra y está protegido por las leyes de propiedad intelectual de la República Argentina y los tratados internacionales aplicables.</p><p>Se concede al usuario una licencia de uso personal, no exclusiva, no transferible y revocable para acceder a la Plataforma con los fines previstos en estos Términos. Queda prohibida la reproducción, distribución, modificación o explotación comercial de cualquier elemento de Ciphra sin autorización previa y por escrito.</p><p>El contenido producido por el propio usuario dentro de la Plataforma (notas, respuestas, ejercicios) permanece bajo su titularidad. Al subirlo o generarlo en Ciphra, el usuario otorga a la Plataforma una licencia limitada para procesarlo con el único fin de prestar el servicio.</p>" },
        { h: "7. Privacidad y Protección de Datos Personales", p: "<p>Ciphra trata los datos personales de sus usuarios en conformidad con la Ley N.º 25.326 de Protección de los Datos Personales de la República Argentina y la normativa complementaria dictada por la Agencia de Acceso a la Información Pública (AAIP).</p><p>Los datos recopilados se utilizan exclusivamente para:</p><ul><li>Brindar y mejorar los servicios de la Plataforma.</li><li>Personalizar la experiencia de aprendizaje del usuario.</li><li>Comunicar novedades relevantes sobre Ciphra (con posibilidad de baja en cualquier momento).</li></ul><p>Ciphra no vende ni cede datos personales a terceros con fines comerciales. Los datos podrán compartirse con proveedores tecnológicos necesarios para el funcionamiento de la Plataforma, bajo acuerdos de confidencialidad.</p><p>El usuario tiene derecho a acceder, rectificar, actualizar y suprimir sus datos personales en cualquier momento, mediante solicitud dirigida a los canales de contacto indicados en la Sección 10.</p>" },
        { h: "8. Disponibilidad del Servicio", p: "<p>Ciphra no garantiza la disponibilidad ininterrumpida de la Plataforma. La Plataforma puede experimentar interrupciones por razones de mantenimiento, actualizaciones técnicas, fuerza mayor u otras causas fuera del control razonable del equipo.</p><p>Ciphra realizará sus mejores esfuerzos para minimizar las interrupciones y comunicarlas con la anticipación posible.</p>" },
        { h: "9. Limitación de Responsabilidad", p: "<p>En la máxima medida permitida por la legislación aplicable, Ciphra no será responsable por:</p><ul><li>Daños directos, indirectos, incidentales o consecuentes derivados del uso o la imposibilidad de uso de la Plataforma.</li><li>Pérdida de datos, interrupciones del servicio o errores en el contenido generado por IA.</li><li>Daños ocasionados por el acceso no autorizado a cuentas de usuario.</li><li>El contenido de sitios web de terceros enlazados desde la Plataforma.</li></ul><p>Esta limitación no aplica en caso de dolo o culpa grave imputable directamente a Ciphra.</p>" },
        { h: "10. Modificaciones a los Términos", p: "<p>Ciphra se reserva el derecho de modificar estos Términos en cualquier momento. Las modificaciones entrarán en vigor a partir de su publicación en la Plataforma. En caso de cambios sustanciales, se notificará a los usuarios registrados por los medios disponibles.</p>" },
        { h: "11. Ley Aplicable y Jurisdicción", p: "<p>Estos Términos se rigen e interpretan de conformidad con las leyes de la República Argentina. Ante cualquier controversia derivada del uso de la Plataforma, las partes se someten a la jurisdicción de los Tribunales Ordinarios de la Ciudad Autónoma de Buenos Aires, con renuncia expresa a cualquier otro fuero que pudiera corresponder.</p>" },
        { h: "12. Contacto", p: `<p>Para consultas, solicitudes relacionadas con datos personales o cualquier comunicación relativa a estos Términos, podés escribirnos a:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}</p>` },
      ],
      en: [
        { h: "1. Acceptance of the Terms", p: "<p>By accessing and using Ciphra (the \"Platform\"), the user fully accepts these Terms & Conditions of Use (the \"Terms\"). If you do not agree with any of these conditions, please refrain from using the Platform.</p><p>Continued use of Ciphra after any modification to these Terms implies acceptance of those modifications.</p>" },
        { h: "2. Service Description", p: "<p>Ciphra is an AI-powered study platform designed to support its users' learning through several interactive modules, including:</p><ul><li><b>MindShift:</b> multi-format assessment system.</li><li><b>Quantum:</b> problem solving with the Socratic method.</li><li><b>Commander:</b> central AI assistant with different capability tiers (Synapse, Apex and Ethos).</li></ul><p>The Platform is under active development. Ciphra reserves the right to add new features, modify existing ones, or discontinue modules without prior notice.</p>" },
        { h: "3. Eligibility and Registration", p: "<p>To use Ciphra, the user must:</p><ul><li>Be at least 13 years old. Users under 18 must have the consent of a parent or legal guardian to register and use the Platform.</li><li>Provide truthful, complete and up-to-date information during registration.</li><li>Keep their access credentials confidential. Ciphra is not responsible for unauthorized account use arising from the user's negligence in protecting their login data.</li></ul>" },
        { h: "4. Acceptable Use", p: "<p>The user agrees to use Ciphra exclusively for educational purposes and in a manner compatible with applicable Argentine law and with these Terms.</p><p>The following is expressly prohibited:</p><ul><li>Using the Platform to generate, distribute or store illegal, misleading, defamatory, obscene content, or content that violates third-party rights.</li><li>Attempting to access restricted areas of the system, breach security mechanisms, or reverse-engineer the Platform.</li><li>Using automated tools (bots, scrapers or others) to extract data from the Platform without express authorization.</li><li>Impersonating other users or members of the Ciphra team.</li><li>Sharing, selling or transferring access credentials to third parties.</li></ul><p>Failure to comply may result in suspension or permanent cancellation of the account, without prejudice to any applicable legal action.</p>" },
        { h: "5. Artificial Intelligence and Limitations", p: "<p>Ciphra integrates third-party AI models to enhance its functionality. The user acknowledges and accepts that:</p><ul><li>Responses generated by AI models are for guidance only and do not replace professional judgment nor constitute formal academic advice.</li><li>AI may make mistakes, produce outdated information, or generate inaccurate responses. Ciphra does not guarantee the accuracy, completeness or suitability of content generated by its AI modules.</li><li>Processing certain data may involve infrastructure of external providers (such as Google LLC or others), subject to their own privacy policies and terms of service.</li></ul><p>The user is solely responsible for the use they make of the content generated by the Platform.</p>" },
        { h: "6. Intellectual Property", p: "<p>All original Ciphra content — including, without limitation, the interface design, source code, logos, institutional texts and module architecture — is the exclusive property of Ciphra and is protected by the intellectual property laws of the Argentine Republic and applicable international treaties.</p><p>The user is granted a personal, non-exclusive, non-transferable and revocable license to access the Platform for the purposes set out in these Terms. Reproduction, distribution, modification or commercial exploitation of any Ciphra element without prior written authorization is prohibited.</p><p>Content produced by the user within the Platform (notes, answers, exercises) remains their property. By uploading or generating it on Ciphra, the user grants the Platform a limited license to process it solely for the purpose of providing the service.</p>" },
        { h: "7. Privacy and Personal Data Protection", p: "<p>Ciphra processes its users' personal data in accordance with Argentina's Personal Data Protection Act No. 25,326 and the complementary regulations issued by the Agency for Access to Public Information (AAIP).</p><p>The collected data is used exclusively to:</p><ul><li>Provide and improve the Platform's services.</li><li>Personalize the user's learning experience.</li><li>Communicate relevant Ciphra news (with the option to unsubscribe at any time).</li></ul><p>Ciphra does not sell or transfer personal data to third parties for commercial purposes. Data may be shared with technology providers necessary for the Platform's operation, under confidentiality agreements.</p><p>The user has the right to access, rectify, update and delete their personal data at any time, by request through the contact channels indicated in Section 10.</p>" },
        { h: "8. Service Availability", p: "<p>Ciphra does not guarantee uninterrupted availability of the Platform. The Platform may experience interruptions due to maintenance, technical updates, force majeure or other causes beyond the team's reasonable control.</p><p>Ciphra will make its best efforts to minimize interruptions and announce them as far in advance as possible.</p>" },
        { h: "9. Limitation of Liability", p: "<p>To the maximum extent permitted by applicable law, Ciphra shall not be liable for:</p><ul><li>Direct, indirect, incidental or consequential damages arising from the use or inability to use the Platform.</li><li>Data loss, service interruptions, or errors in AI-generated content.</li><li>Damages caused by unauthorized access to user accounts.</li><li>The content of third-party websites linked from the Platform.</li></ul><p>This limitation does not apply in cases of willful misconduct or gross negligence directly attributable to Ciphra.</p>" },
        { h: "10. Changes to the Terms", p: "<p>Ciphra reserves the right to modify these Terms at any time. Modifications take effect upon publication on the Platform. In case of substantial changes, registered users will be notified through available means.</p>" },
        { h: "11. Governing Law and Jurisdiction", p: "<p>These Terms are governed by and construed in accordance with the laws of the Argentine Republic. For any dispute arising from the use of the Platform, the parties submit to the jurisdiction of the Ordinary Courts of the Autonomous City of Buenos Aires, expressly waiving any other jurisdiction that might apply.</p>" },
        { h: "12. Contact", p: `<p>For inquiries, requests related to personal data, or any communication regarding these Terms, you can write to us at:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}</p>` },
      ],
      pt: [
        { h: "1. Aceitação dos Termos", p: "<p>Ao acessar e utilizar a Ciphra (doravante, \"a Plataforma\"), o usuário aceita integralmente os presentes Termos e Condições de Uso (doravante, \"os Termos\"). Se você não concorda com alguma destas condições, pedimos que se abstenha de utilizar a Plataforma.</p><p>O uso continuado da Ciphra após qualquer modificação destes Termos implica a aceitação de tais modificações.</p>" },
        { h: "2. Descrição do Serviço", p: "<p>A Ciphra é uma plataforma de estudo potencializada por inteligência artificial, projetada para acompanhar o aprendizado de seus usuários por meio de diversos módulos interativos, entre eles:</p><ul><li><b>MindShift:</b> sistema de avaliação em múltiplos formatos.</li><li><b>Quantum:</b> resolução de problemas com metodologia socrática.</li><li><b>Commander:</b> assistente de IA central com diferentes níveis de capacidade (Synapse, Apex e Ethos).</li></ul><p>A Plataforma está em desenvolvimento ativo. A Ciphra se reserva o direito de incorporar novas funções, modificar as existentes ou descontinuar módulos sem aviso prévio.</p>" },
        { h: "3. Elegibilidade e Cadastro", p: "<p>Para utilizar a Ciphra, o usuário deve:</p><ul><li>Ter pelo menos 13 anos de idade. Os menores de 18 anos deverão ter o consentimento de um pai, mãe ou responsável legal para se cadastrar e utilizar a Plataforma.</li><li>Fornecer informações verdadeiras, completas e atualizadas durante o cadastro.</li><li>Manter a confidencialidade de suas credenciais de acesso. A Ciphra não se responsabiliza pelo uso não autorizado de uma conta decorrente da negligência do usuário na proteção de seus dados de acesso.</li></ul>" },
        { h: "4. Uso Aceitável", p: "<p>O usuário se compromete a utilizar a Ciphra exclusivamente para fins educacionais e de maneira compatível com a legislação argentina vigente e com estes Termos.</p><p>É expressamente proibido:</p><ul><li>Utilizar a Plataforma para gerar, distribuir ou armazenar conteúdo ilegal, enganoso, difamatório, obsceno ou que viole direitos de terceiros.</li><li>Tentar acessar áreas restritas do sistema, violar mecanismos de segurança ou realizar engenharia reversa na Plataforma.</li><li>Usar ferramentas automatizadas (bots, scrapers ou outras) para extrair dados da Plataforma sem autorização expressa.</li><li>Falsificar a identidade de outros usuários ou de integrantes da equipe da Ciphra.</li><li>Compartilhar, vender ou ceder credenciais de acesso a terceiros.</li></ul><p>O descumprimento destas condições poderá resultar na suspensão ou cancelamento permanente da conta, sem prejuízo das ações legais cabíveis.</p>" },
        { h: "5. Inteligência Artificial e Limitações", p: "<p>A Ciphra integra modelos de inteligência artificial de terceiros para potencializar sua funcionalidade. O usuário reconhece e aceita que:</p><ul><li>As respostas geradas pelos modelos de IA têm caráter orientativo e não substituem o critério de um profissional nem constituem assessoria acadêmica formal.</li><li>A IA pode cometer erros, gerar informações desatualizadas ou produzir respostas imprecisas. A Ciphra não garante a exatidão, integridade nem adequação do conteúdo gerado por seus módulos de IA.</li><li>O processamento de certos dados pode envolver infraestrutura de provedores externos (como Google LLC ou outros), sujeito às suas próprias políticas de privacidade e termos de serviço.</li></ul><p>O usuário é o único responsável pelo uso que fizer do conteúdo gerado pela Plataforma.</p>" },
        { h: "6. Propriedade Intelectual", p: "<p>Todo o conteúdo original da Ciphra — incluindo, sem limitação, o design da interface, o código-fonte, os logotipos, os textos institucionais e a arquitetura dos módulos — é propriedade exclusiva da Ciphra e está protegido pelas leis de propriedade intelectual da República Argentina e pelos tratados internacionais aplicáveis.</p><p>Concede-se ao usuário uma licença de uso pessoal, não exclusiva, intransferível e revogável para acessar a Plataforma com os fins previstos nestes Termos. É proibida a reprodução, distribuição, modificação ou exploração comercial de qualquer elemento da Ciphra sem autorização prévia e por escrito.</p><p>O conteúdo produzido pelo próprio usuário dentro da Plataforma (notas, respostas, exercícios) permanece sob sua titularidade. Ao enviá-lo ou gerá-lo na Ciphra, o usuário concede à Plataforma uma licença limitada para processá-lo com o único fim de prestar o serviço.</p>" },
        { h: "7. Privacidade e Proteção de Dados Pessoais", p: "<p>A Ciphra trata os dados pessoais de seus usuários em conformidade com a Lei n.º 25.326 de Proteção dos Dados Pessoais da República Argentina e a normativa complementar emitida pela Agência de Acesso à Informação Pública (AAIP).</p><p>Os dados coletados são utilizados exclusivamente para:</p><ul><li>Fornecer e melhorar os serviços da Plataforma.</li><li>Personalizar a experiência de aprendizado do usuário.</li><li>Comunicar novidades relevantes sobre a Ciphra (com possibilidade de cancelamento a qualquer momento).</li></ul><p>A Ciphra não vende nem cede dados pessoais a terceiros com fins comerciais. Os dados poderão ser compartilhados com provedores tecnológicos necessários para o funcionamento da Plataforma, sob acordos de confidencialidade.</p><p>O usuário tem o direito de acessar, retificar, atualizar e suprimir seus dados pessoais a qualquer momento, mediante solicitação dirigida aos canais de contato indicados na Seção 10.</p>" },
        { h: "8. Disponibilidade do Serviço", p: "<p>A Ciphra não garante a disponibilidade ininterrupta da Plataforma. A Plataforma pode sofrer interrupções por motivos de manutenção, atualizações técnicas, força maior ou outras causas fora do controle razoável da equipe.</p><p>A Ciphra envidará seus melhores esforços para minimizar as interrupções e comunicá-las com a maior antecedência possível.</p>" },
        { h: "9. Limitação de Responsabilidade", p: "<p>Na máxima medida permitida pela legislação aplicável, a Ciphra não será responsável por:</p><ul><li>Danos diretos, indiretos, incidentais ou consequentes decorrentes do uso ou da impossibilidade de uso da Plataforma.</li><li>Perda de dados, interrupções do serviço ou erros no conteúdo gerado por IA.</li><li>Danos causados pelo acesso não autorizado a contas de usuário.</li><li>O conteúdo de sites de terceiros vinculados a partir da Plataforma.</li></ul><p>Esta limitação não se aplica em caso de dolo ou culpa grave imputável diretamente à Ciphra.</p>" },
        { h: "10. Modificações aos Termos", p: "<p>A Ciphra se reserva o direito de modificar estes Termos a qualquer momento. As modificações entrarão em vigor a partir de sua publicação na Plataforma. Em caso de mudanças substanciais, os usuários cadastrados serão notificados pelos meios disponíveis.</p>" },
        { h: "11. Lei Aplicável e Jurisdição", p: "<p>Estes Termos são regidos e interpretados em conformidade com as leis da República Argentina. Diante de qualquer controvérsia decorrente do uso da Plataforma, as partes se submetem à jurisdição dos Tribunais Ordinários da Cidade Autônoma de Buenos Aires, com renúncia expressa a qualquer outro foro que possa corresponder.</p>" },
        { h: "12. Contato", p: `<p>Para consultas, solicitações relacionadas a dados pessoais ou qualquer comunicação relativa a estes Termos, você pode escrever para:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}</p>` },
      ],
    },

    privacidad: {
      es: [
        { h: "1. Introducción", p: "<p>En Ciphra valoramos la privacidad de nuestros usuarios y nos comprometemos a tratar sus datos personales con transparencia, responsabilidad y seguridad. Esta Política de Privacidad (en adelante, \"la Política\") describe qué datos recopilamos, cómo los usamos, con quién los compartimos y qué derechos te asisten como usuario.</p><p>Esta Política forma parte integrante de los Términos y Condiciones de Uso de Ciphra y debe leerse en conjunto con ellos.</p><p>El uso de la Plataforma implica la aceptación de esta Política. Si no estás de acuerdo con su contenido, te pedimos que no utilices Ciphra.</p>" },
        { h: "2. Responsable del Tratamiento", p: `<p>El responsable del tratamiento de los datos personales recabados a través de Ciphra es:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}<br>📍 Ciudad Autónoma de Buenos Aires, Argentina</p>` },
        { h: "3. Marco Legal Aplicable", p: "<p>Esta Política se rige por la Ley N.º 25.326 de Protección de los Datos Personales de la República Argentina, su decreto reglamentario N.º 1558/2001 y las disposiciones complementarias emitidas por la Agencia de Acceso a la Información Pública (AAIP), autoridad de control en materia de protección de datos personales en Argentina.</p>" },
        { h: "4. Datos que Recopilamos", p: "<p>Ciphra puede recopilar las siguientes categorías de datos personales:</p><p><b>4.1 Datos que nos proporcionás directamente</b></p><ul><li><b>Datos de registro:</b> nombre o nombre de usuario, dirección de correo electrónico y contraseña.</li><li><b>Datos de perfil:</b> nivel educativo, materias de interés u otra información que el usuario elija incorporar voluntariamente.</li><li><b>Comunicaciones:</b> mensajes enviados a través de los canales de contacto de Ciphra.</li></ul><p><b>4.2 Datos generados por el uso de la Plataforma</b></p><ul><li><b>Contenido del usuario:</b> notas, respuestas a ejercicios, interacciones con los módulos (MindShift, Quantum, Commander) y demás material producido dentro de la Plataforma.</li><li><b>Datos de uso:</b> páginas visitadas, funciones utilizadas, frecuencia y duración de las sesiones, preferencias de configuración.</li><li><b>Datos técnicos:</b> dirección IP, tipo y versión de navegador, sistema operativo, identificadores de dispositivo y zona horaria.</li></ul><p><b>4.3 Datos recopilados mediante tecnologías automáticas</b></p><ul><li><b>Cookies y tecnologías similares:</b> utilizadas para mantener la sesión activa, recordar preferencias y mejorar la experiencia del usuario. Para más detalle, consultá la Sección 9.</li></ul>" },
        { h: "5. Finalidad del Tratamiento", p: "<p>Los datos personales recopilados se utilizan para los siguientes fines:</p><ul><li>Crear y gestionar tu cuenta en la Plataforma — <i>ejecución del contrato</i>.</li><li>Prestar los servicios de Ciphra y personalizar tu experiencia de aprendizaje — <i>ejecución del contrato</i>.</li><li>Mejorar y desarrollar nuevas funcionalidades — <i>interés legítimo</i>.</li><li>Comunicar novedades, actualizaciones y cambios relevantes del servicio — <i>interés legítimo / consentimiento</i>.</li><li>Garantizar la seguridad de la Plataforma y prevenir usos fraudulentos — <i>obligación legal / interés legítimo</i>.</li><li>Cumplir obligaciones legales aplicables — <i>obligación legal</i>.</li><li>Procesar consultas y solicitudes enviadas por el usuario — <i>ejecución del contrato / consentimiento</i>.</li></ul><p>Ciphra no utiliza los datos personales de sus usuarios con fines publicitarios propios ni los cede a terceros para ese fin.</p>" },
        { h: "6. Inteligencia Artificial y Datos del Usuario", p: "<p>Ciphra integra modelos de inteligencia artificial de terceros (actualmente, servicios de Google LLC, entre otros) para el funcionamiento de sus módulos. El usuario reconoce y acepta que:</p><ul><li>Las interacciones con los módulos de IA (como Commander, Quantum y MindShift) pueden ser procesadas por infraestructura de proveedores externos.</li><li>Ciphra no utiliza el contenido de las conversaciones del usuario para entrenar modelos de IA propios, salvo que se obtenga consentimiento expreso e informado para ese fin.</li><li>Los proveedores de IA cuentan con sus propias políticas de privacidad, que te recomendamos revisar.</li></ul><p>Te recomendamos no compartir información sensible —datos de salud, financieros, documentos de identidad u otros de carácter reservado— a través de los módulos de IA de la Plataforma.</p>" },
        { h: "7. Compartición de Datos con Terceros", p: "<p>Ciphra no vende ni alquila datos personales. Los datos podrán ser compartidos únicamente en los siguientes supuestos:</p><p><b>7.1 Proveedores de servicios.</b> Ciphra trabaja con proveedores tecnológicos que actúan como encargados del tratamiento, incluyendo servicios de infraestructura en la nube, modelos de IA y herramientas de análisis. Estos proveedores están contractualmente obligados a tratar los datos únicamente conforme a las instrucciones de Ciphra y a mantener medidas de seguridad adecuadas. Entre los proveedores actuales o potenciales se encuentran Google LLC (servicios de IA y/o infraestructura en la nube) y otros proveedores que puedan incorporarse durante el desarrollo de la Plataforma.</p><p><b>7.2 Obligaciones legales.</b> Ciphra podrá divulgar datos personales cuando así lo exija una autoridad competente en el marco de un proceso legal, una orden judicial o una obligación normativa aplicable.</p><p><b>7.3 Cesión o fusión empresarial.</b> En caso de fusión, adquisición o transferencia total o parcial de los activos de Ciphra, los datos personales podrán ser transferidos al nuevo responsable, quien quedará obligado a respetar esta Política o a notificar a los usuarios cualquier cambio sustancial.</p>" },
        { h: "8. Transferencias Internacionales de Datos", p: "<p>Algunos de nuestros proveedores tecnológicos pueden estar radicados fuera de la República Argentina, lo que implica la transferencia internacional de datos personales. En tales casos, Ciphra adopta las medidas contractuales necesarias para garantizar un nivel de protección adecuado, conforme a lo establecido por la AAIP.</p>" },
        { h: "9. Cookies y Tecnologías Similares", p: "<p>Ciphra utiliza cookies y tecnologías equivalentes para:</p><ul><li><b>Cookies esenciales:</b> necesarias para el funcionamiento básico de la Plataforma (por ejemplo, mantener la sesión iniciada). No pueden desactivarse sin afectar el servicio.</li><li><b>Cookies de preferencias:</b> recuerdan configuraciones y preferencias del usuario para personalizar su experiencia.</li><li><b>Cookies analíticas:</b> recopilan información agregada sobre el uso de la Plataforma para identificar áreas de mejora. No identifican al usuario de forma individual.</li></ul><p>El usuario puede gestionar o desactivar las cookies no esenciales desde la configuración de su navegador, aunque esto puede afectar la experiencia de uso de algunas funcionalidades.</p>" },
        { h: "10. Conservación de los Datos", p: "<p>Los datos personales se conservan durante el tiempo necesario para cumplir con las finalidades descritas en esta Política, o mientras el usuario mantenga una cuenta activa en la Plataforma.</p><p>Una vez que la cuenta sea eliminada o transcurra el período de conservación aplicable, los datos serán suprimidos o anonimizados, salvo que su conservación sea necesaria para cumplir obligaciones legales o para la defensa ante posibles reclamos.</p>" },
        { h: "11. Seguridad de los Datos", p: "<p>Ciphra implementa medidas técnicas y organizativas razonables para proteger los datos personales de sus usuarios frente a accesos no autorizados, pérdida, alteración o divulgación indebida.</p><p>Sin perjuicio de lo anterior, ningún sistema de seguridad es infalible. En caso de un incidente de seguridad que afecte datos personales, Ciphra notificará a los usuarios y a la AAIP en los términos exigidos por la normativa vigente.</p>" },
        { h: "12. Menores de Edad", p: "<p>Ciphra no está dirigida a menores de 13 años. Los usuarios de entre 13 y 17 años deben contar con el consentimiento de un padre, madre o tutor legal para registrarse y utilizar la Plataforma.</p><p>Si tomamos conocimiento de que hemos recopilado datos de un menor de 13 años sin consentimiento verificable, procederemos a eliminar dicha información a la brevedad. Para reportar este tipo de situación, contactanos en los canales indicados en la Sección 14.</p>" },
        { h: "13. Derechos del Usuario", p: "<p>En virtud de la Ley N.º 25.326, el usuario tiene derecho a:</p><ul><li><b>Acceso:</b> conocer qué datos personales suyos trata Ciphra, de dónde provienen y con qué finalidad.</li><li><b>Rectificación:</b> solicitar la corrección de datos inexactos, incompletos o desactualizados.</li><li><b>Supresión:</b> solicitar la eliminación de sus datos cuando ya no sean necesarios, o cuando retire el consentimiento oportunamente otorgado.</li><li><b>Confidencialidad:</b> exigir que sus datos no sean cedidos a terceros en los casos no previstos por la ley o esta Política.</li><li><b>Oposición:</b> oponerse al tratamiento de sus datos para determinadas finalidades, en los casos que la ley lo permita.</li></ul><p>Para ejercer cualquiera de estos derechos, el usuario puede enviar una solicitud al correo de contacto indicado en la Sección 14, identificándose adecuadamente. Ciphra responderá en el plazo máximo establecido por la normativa vigente.</p><p>La AAIP es la autoridad de control competente ante la cual el usuario puede presentar reclamos si considera que el tratamiento de sus datos no se ajusta a la normativa aplicable.</p><p style=\"font-size:0.82rem;opacity:0.7\">EL TITULAR DE LOS DATOS PERSONALES TIENE LA FACULTAD DE EJERCER EL DERECHO DE ACCESO A LOS MISMOS EN FORMA GRATUITA A INTERVALOS NO INFERIORES A SEIS MESES, SALVO QUE SE ACREDITE UN INTERÉS LEGÍTIMO AL EFECTO CONFORME LO ESTABLECIDO EN EL ARTÍCULO 14, INCISO 3 DE LA LEY N.º 25.326.</p>" },
        { h: "14. Contacto", p: `<p>Para ejercer tus derechos, realizar consultas o reportar cualquier inquietud relacionada con tu privacidad, podés contactarnos en:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}</p><p>Responderemos tu solicitud a la brevedad posible y en ningún caso más allá del plazo legal establecido.</p>` },
        { h: "15. Modificaciones a esta Política", p: "<p>Ciphra se reserva el derecho de actualizar esta Política cuando lo considere necesario, ya sea por cambios en el servicio, en la normativa aplicable o en las prácticas de tratamiento de datos. Toda modificación será publicada en la Plataforma con indicación de la fecha de actualización.</p><p>Para cambios sustanciales, notificaremos a los usuarios registrados por los medios disponibles con antelación razonable.</p>" },
      ],
      en: [
        { h: "1. Introduction", p: "<p>At Ciphra we value our users' privacy and are committed to processing their personal data with transparency, responsibility and security. This Privacy Policy (the \"Policy\") describes what data we collect, how we use it, who we share it with, and what rights you have as a user.</p><p>This Policy is an integral part of Ciphra's Terms & Conditions of Use and must be read together with them.</p><p>Use of the Platform implies acceptance of this Policy. If you do not agree with its content, please do not use Ciphra.</p>" },
        { h: "2. Data Controller", p: `<p>The party responsible for processing the personal data collected through Ciphra is:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}<br>📍 Autonomous City of Buenos Aires, Argentina</p>` },
        { h: "3. Applicable Legal Framework", p: "<p>This Policy is governed by Argentina's Personal Data Protection Act No. 25,326, its regulatory decree No. 1558/2001, and the complementary provisions issued by the Agency for Access to Public Information (AAIP), the supervisory authority for personal data protection in Argentina.</p>" },
        { h: "4. Data We Collect", p: "<p>Ciphra may collect the following categories of personal data:</p><p><b>4.1 Data you provide directly</b></p><ul><li><b>Registration data:</b> name or username, email address and password.</li><li><b>Profile data:</b> educational level, subjects of interest, or other information the user chooses to add voluntarily.</li><li><b>Communications:</b> messages sent through Ciphra's contact channels.</li></ul><p><b>4.2 Data generated by use of the Platform</b></p><ul><li><b>User content:</b> notes, exercise answers, interactions with the modules (MindShift, Quantum, Commander) and other material produced within the Platform.</li><li><b>Usage data:</b> pages visited, features used, frequency and duration of sessions, configuration preferences.</li><li><b>Technical data:</b> IP address, browser type and version, operating system, device identifiers and time zone.</li></ul><p><b>4.3 Data collected via automatic technologies</b></p><ul><li><b>Cookies and similar technologies:</b> used to keep the session active, remember preferences and improve the user experience. See Section 9 for details.</li></ul>" },
        { h: "5. Purpose of Processing", p: "<p>The collected personal data is used for the following purposes:</p><ul><li>Create and manage your account on the Platform — <i>contract performance</i>.</li><li>Provide Ciphra's services and personalize your learning experience — <i>contract performance</i>.</li><li>Improve and develop new features — <i>legitimate interest</i>.</li><li>Communicate news, updates and relevant service changes — <i>legitimate interest / consent</i>.</li><li>Ensure the Platform's security and prevent fraudulent use — <i>legal obligation / legitimate interest</i>.</li><li>Comply with applicable legal obligations — <i>legal obligation</i>.</li><li>Process inquiries and requests sent by the user — <i>contract performance / consent</i>.</li></ul><p>Ciphra does not use its users' personal data for its own advertising purposes nor transfer it to third parties for that purpose.</p>" },
        { h: "6. Artificial Intelligence and User Data", p: "<p>Ciphra integrates third-party AI models (currently Google LLC services, among others) for the operation of its modules. The user acknowledges and accepts that:</p><ul><li>Interactions with the AI modules (such as Commander, Quantum and MindShift) may be processed by external providers' infrastructure.</li><li>Ciphra does not use the content of user conversations to train its own AI models, unless express and informed consent is obtained for that purpose.</li><li>AI providers have their own privacy policies, which we recommend you review.</li></ul><p>We recommend not sharing sensitive information — health, financial, identity documents or other confidential data — through the Platform's AI modules.</p>" },
        { h: "7. Data Sharing with Third Parties", p: "<p>Ciphra does not sell or rent personal data. Data may be shared only in the following cases:</p><p><b>7.1 Service providers.</b> Ciphra works with technology providers acting as data processors, including cloud infrastructure services, AI models and analytics tools. These providers are contractually obligated to process the data solely according to Ciphra's instructions and to maintain adequate security measures. Current or potential providers include Google LLC (AI and/or cloud infrastructure services) and others that may be incorporated during the Platform's development.</p><p><b>7.2 Legal obligations.</b> Ciphra may disclose personal data when required by a competent authority in the context of legal proceedings, a court order, or an applicable regulatory obligation.</p><p><b>7.3 Business transfer or merger.</b> In the event of a merger, acquisition or full or partial transfer of Ciphra's assets, personal data may be transferred to the new controller, who will be obligated to respect this Policy or notify users of any substantial change.</p>" },
        { h: "8. International Data Transfers", p: "<p>Some of our technology providers may be located outside the Argentine Republic, which implies the international transfer of personal data. In such cases, Ciphra adopts the necessary contractual measures to guarantee an adequate level of protection, in accordance with AAIP requirements.</p>" },
        { h: "9. Cookies and Similar Technologies", p: "<p>Ciphra uses cookies and equivalent technologies for:</p><ul><li><b>Essential cookies:</b> necessary for the basic operation of the Platform (e.g., keeping the session logged in). They cannot be disabled without affecting the service.</li><li><b>Preference cookies:</b> remember the user's settings and preferences to personalize their experience.</li><li><b>Analytics cookies:</b> collect aggregated information about Platform use to identify areas for improvement. They do not identify the user individually.</li></ul><p>The user can manage or disable non-essential cookies from their browser settings, although this may affect the experience of some features.</p>" },
        { h: "10. Data Retention", p: "<p>Personal data is retained for the time necessary to fulfill the purposes described in this Policy, or while the user maintains an active account on the Platform.</p><p>Once the account is deleted or the applicable retention period elapses, the data will be deleted or anonymized, unless its retention is necessary to comply with legal obligations or to defend against possible claims.</p>" },
        { h: "11. Data Security", p: "<p>Ciphra implements reasonable technical and organizational measures to protect its users' personal data against unauthorized access, loss, alteration or improper disclosure.</p><p>Notwithstanding the above, no security system is infallible. In the event of a security incident affecting personal data, Ciphra will notify users and the AAIP under the terms required by current regulations.</p>" },
        { h: "12. Minors", p: "<p>Ciphra is not directed at children under 13. Users between 13 and 17 must have the consent of a parent or legal guardian to register and use the Platform.</p><p>If we become aware that we have collected data from a child under 13 without verifiable consent, we will delete that information promptly. To report such a situation, contact us through the channels indicated in Section 14.</p>" },
        { h: "13. User Rights", p: "<p>Under Act No. 25,326, the user has the right to:</p><ul><li><b>Access:</b> know what personal data of theirs Ciphra processes, where it comes from and for what purpose.</li><li><b>Rectification:</b> request the correction of inaccurate, incomplete or outdated data.</li><li><b>Deletion:</b> request the deletion of their data when no longer necessary, or upon withdrawal of previously given consent.</li><li><b>Confidentiality:</b> require that their data not be transferred to third parties in cases not provided for by law or this Policy.</li><li><b>Objection:</b> object to the processing of their data for certain purposes, where the law allows.</li></ul><p>To exercise any of these rights, the user can send a request to the contact email indicated in Section 14, identifying themselves appropriately. Ciphra will respond within the maximum period established by current regulations.</p><p>The AAIP is the competent supervisory authority before which the user may file complaints if they consider that the processing of their data does not comply with applicable regulations.</p><p style=\"font-size:0.82rem;opacity:0.7\">THE OWNER OF THE PERSONAL DATA HAS THE RIGHT TO EXERCISE THE RIGHT OF ACCESS TO IT FREE OF CHARGE AT INTERVALS NO SHORTER THAN SIX MONTHS, UNLESS A LEGITIMATE INTEREST IS DEMONSTRATED, AS ESTABLISHED IN ARTICLE 14, SUBSECTION 3 OF ACT No. 25,326.</p>" },
        { h: "14. Contact", p: `<p>To exercise your rights, make inquiries or report any concern related to your privacy, you can contact us at:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}</p><p>We will respond to your request as soon as possible and in no case beyond the established legal deadline.</p>` },
        { h: "15. Changes to this Policy", p: "<p>Ciphra reserves the right to update this Policy whenever it deems necessary, whether due to changes in the service, applicable regulations or data processing practices. Any modification will be published on the Platform with the date of update.</p><p>For substantial changes, we will notify registered users through available means with reasonable advance notice.</p>" },
      ],
      pt: [
        { h: "1. Introdução", p: "<p>Na Ciphra valorizamos a privacidade de nossos usuários e nos comprometemos a tratar seus dados pessoais com transparência, responsabilidade e segurança. Esta Política de Privacidade (doravante, \"a Política\") descreve quais dados coletamos, como os usamos, com quem os compartilhamos e quais direitos você tem como usuário.</p><p>Esta Política é parte integrante dos Termos e Condições de Uso da Ciphra e deve ser lida em conjunto com eles.</p><p>O uso da Plataforma implica a aceitação desta Política. Se você não concorda com seu conteúdo, pedimos que não utilize a Ciphra.</p>" },
        { h: "2. Responsável pelo Tratamento", p: `<p>O responsável pelo tratamento dos dados pessoais coletados através da Ciphra é:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}<br>📍 Cidade Autônoma de Buenos Aires, Argentina</p>` },
        { h: "3. Marco Legal Aplicável", p: "<p>Esta Política é regida pela Lei n.º 25.326 de Proteção dos Dados Pessoais da República Argentina, seu decreto regulamentar n.º 1558/2001 e as disposições complementares emitidas pela Agência de Acesso à Informação Pública (AAIP), autoridade de controle em matéria de proteção de dados pessoais na Argentina.</p>" },
        { h: "4. Dados que Coletamos", p: "<p>A Ciphra pode coletar as seguintes categorias de dados pessoais:</p><p><b>4.1 Dados que você nos fornece diretamente</b></p><ul><li><b>Dados de cadastro:</b> nome ou nome de usuário, endereço de e-mail e senha.</li><li><b>Dados de perfil:</b> nível educacional, matérias de interesse ou outras informações que o usuário escolha incorporar voluntariamente.</li><li><b>Comunicações:</b> mensagens enviadas através dos canais de contato da Ciphra.</li></ul><p><b>4.2 Dados gerados pelo uso da Plataforma</b></p><ul><li><b>Conteúdo do usuário:</b> notas, respostas a exercícios, interações com os módulos (MindShift, Quantum, Commander) e demais material produzido dentro da Plataforma.</li><li><b>Dados de uso:</b> páginas visitadas, funções utilizadas, frequência e duração das sessões, preferências de configuração.</li><li><b>Dados técnicos:</b> endereço IP, tipo e versão do navegador, sistema operacional, identificadores de dispositivo e fuso horário.</li></ul><p><b>4.3 Dados coletados por tecnologias automáticas</b></p><ul><li><b>Cookies e tecnologias similares:</b> utilizadas para manter a sessão ativa, lembrar preferências e melhorar a experiência do usuário. Para mais detalhes, consulte a Seção 9.</li></ul>" },
        { h: "5. Finalidade do Tratamento", p: "<p>Os dados pessoais coletados são utilizados para as seguintes finalidades:</p><ul><li>Criar e gerenciar sua conta na Plataforma — <i>execução do contrato</i>.</li><li>Prestar os serviços da Ciphra e personalizar sua experiência de aprendizado — <i>execução do contrato</i>.</li><li>Melhorar e desenvolver novas funcionalidades — <i>interesse legítimo</i>.</li><li>Comunicar novidades, atualizações e mudanças relevantes do serviço — <i>interesse legítimo / consentimento</i>.</li><li>Garantir a segurança da Plataforma e prevenir usos fraudulentos — <i>obrigação legal / interesse legítimo</i>.</li><li>Cumprir obrigações legais aplicáveis — <i>obrigação legal</i>.</li><li>Processar consultas e solicitações enviadas pelo usuário — <i>execução do contrato / consentimento</i>.</li></ul><p>A Ciphra não utiliza os dados pessoais de seus usuários com fins publicitários próprios nem os cede a terceiros para esse fim.</p>" },
        { h: "6. Inteligência Artificial e Dados do Usuário", p: "<p>A Ciphra integra modelos de inteligência artificial de terceiros (atualmente, serviços do Google LLC, entre outros) para o funcionamento de seus módulos. O usuário reconhece e aceita que:</p><ul><li>As interações com os módulos de IA (como Commander, Quantum e MindShift) podem ser processadas por infraestrutura de provedores externos.</li><li>A Ciphra não utiliza o conteúdo das conversas do usuário para treinar modelos de IA próprios, salvo se obtido consentimento expresso e informado para esse fim.</li><li>Os provedores de IA possuem suas próprias políticas de privacidade, que recomendamos revisar.</li></ul><p>Recomendamos não compartilhar informações sensíveis — dados de saúde, financeiros, documentos de identidade ou outros de caráter reservado — através dos módulos de IA da Plataforma.</p>" },
        { h: "7. Compartilhamento de Dados com Terceiros", p: "<p>A Ciphra não vende nem aluga dados pessoais. Os dados poderão ser compartilhados unicamente nos seguintes casos:</p><p><b>7.1 Provedores de serviços.</b> A Ciphra trabalha com provedores tecnológicos que atuam como operadores de tratamento, incluindo serviços de infraestrutura em nuvem, modelos de IA e ferramentas de análise. Esses provedores estão contratualmente obrigados a tratar os dados unicamente conforme as instruções da Ciphra e a manter medidas de segurança adequadas. Entre os provedores atuais ou potenciais estão o Google LLC (serviços de IA e/ou infraestrutura em nuvem) e outros que possam ser incorporados durante o desenvolvimento da Plataforma.</p><p><b>7.2 Obrigações legais.</b> A Ciphra poderá divulgar dados pessoais quando exigido por autoridade competente no âmbito de um processo legal, ordem judicial ou obrigação normativa aplicável.</p><p><b>7.3 Cessão ou fusão empresarial.</b> Em caso de fusão, aquisição ou transferência total ou parcial dos ativos da Ciphra, os dados pessoais poderão ser transferidos ao novo responsável, que ficará obrigado a respeitar esta Política ou a notificar os usuários sobre qualquer mudança substancial.</p>" },
        { h: "8. Transferências Internacionais de Dados", p: "<p>Alguns de nossos provedores tecnológicos podem estar sediados fora da República Argentina, o que implica a transferência internacional de dados pessoais. Nesses casos, a Ciphra adota as medidas contratuais necessárias para garantir um nível de proteção adequado, conforme estabelecido pela AAIP.</p>" },
        { h: "9. Cookies e Tecnologias Similares", p: "<p>A Ciphra utiliza cookies e tecnologias equivalentes para:</p><ul><li><b>Cookies essenciais:</b> necessários para o funcionamento básico da Plataforma (por exemplo, manter a sessão iniciada). Não podem ser desativados sem afetar o serviço.</li><li><b>Cookies de preferências:</b> lembram configurações e preferências do usuário para personalizar sua experiência.</li><li><b>Cookies analíticos:</b> coletam informações agregadas sobre o uso da Plataforma para identificar áreas de melhoria. Não identificam o usuário de forma individual.</li></ul><p>O usuário pode gerenciar ou desativar os cookies não essenciais nas configurações de seu navegador, embora isso possa afetar a experiência de uso de algumas funcionalidades.</p>" },
        { h: "10. Conservação dos Dados", p: "<p>Os dados pessoais são conservados durante o tempo necessário para cumprir as finalidades descritas nesta Política, ou enquanto o usuário mantiver uma conta ativa na Plataforma.</p><p>Uma vez que a conta seja excluída ou decorra o período de conservação aplicável, os dados serão suprimidos ou anonimizados, salvo se sua conservação for necessária para cumprir obrigações legais ou para a defesa diante de possíveis reclamações.</p>" },
        { h: "11. Segurança dos Dados", p: "<p>A Ciphra implementa medidas técnicas e organizacionais razoáveis para proteger os dados pessoais de seus usuários contra acessos não autorizados, perda, alteração ou divulgação indevida.</p><p>Sem prejuízo do exposto, nenhum sistema de segurança é infalível. Em caso de incidente de segurança que afete dados pessoais, a Ciphra notificará os usuários e a AAIP nos termos exigidos pela normativa vigente.</p>" },
        { h: "12. Menores de Idade", p: "<p>A Ciphra não é dirigida a menores de 13 anos. Os usuários entre 13 e 17 anos devem ter o consentimento de um pai, mãe ou responsável legal para se cadastrar e utilizar a Plataforma.</p><p>Se tomarmos conhecimento de que coletamos dados de um menor de 13 anos sem consentimento verificável, procederemos à eliminação dessa informação o mais breve possível. Para relatar esse tipo de situação, entre em contato pelos canais indicados na Seção 14.</p>" },
        { h: "13. Direitos do Usuário", p: "<p>Em virtude da Lei n.º 25.326, o usuário tem direito a:</p><ul><li><b>Acesso:</b> saber quais dados pessoais seus a Ciphra trata, de onde provêm e com que finalidade.</li><li><b>Retificação:</b> solicitar a correção de dados inexatos, incompletos ou desatualizados.</li><li><b>Supressão:</b> solicitar a eliminação de seus dados quando já não sejam necessários, ou quando retirar o consentimento oportunamente concedido.</li><li><b>Confidencialidade:</b> exigir que seus dados não sejam cedidos a terceiros nos casos não previstos pela lei ou por esta Política.</li><li><b>Oposição:</b> opor-se ao tratamento de seus dados para determinadas finalidades, nos casos em que a lei permita.</li></ul><p>Para exercer qualquer destes direitos, o usuário pode enviar uma solicitação ao e-mail de contato indicado na Seção 14, identificando-se adequadamente. A Ciphra responderá no prazo máximo estabelecido pela normativa vigente.</p><p>A AAIP é a autoridade de controle competente perante a qual o usuário pode apresentar reclamações se considerar que o tratamento de seus dados não está de acordo com a normativa aplicável.</p><p style=\"font-size:0.82rem;opacity:0.7\">O TITULAR DOS DADOS PESSOAIS TEM A FACULDADE DE EXERCER O DIREITO DE ACESSO AOS MESMOS DE FORMA GRATUITA EM INTERVALOS NÃO INFERIORES A SEIS MESES, SALVO SE COMPROVADO UM INTERESSE LEGÍTIMO PARA TAL, CONFORME ESTABELECIDO NO ARTIGO 14, INCISO 3 DA LEI N.º 25.326.</p>" },
        { h: "14. Contato", p: `<p>Para exercer seus direitos, fazer consultas ou relatar qualquer preocupação relacionada à sua privacidade, você pode nos contatar em:</p><p>Ciphra<br>📧 ${CONTACT_EMAIL}<br>🌐 ${SITE}</p><p>Responderemos sua solicitação o mais breve possível e em nenhum caso além do prazo legal estabelecido.</p>` },
        { h: "15. Modificações nesta Política", p: "<p>A Ciphra se reserva o direito de atualizar esta Política quando considerar necessário, seja por mudanças no serviço, na normativa aplicável ou nas práticas de tratamento de dados. Toda modificação será publicada na Plataforma com indicação da data de atualização.</p><p>Para mudanças substanciais, notificaremos os usuários cadastrados pelos meios disponíveis com antecedência razoável.</p>" },
      ],
    },
  };

  window.LEGAL = LEGAL;
})();
